@echo off
cls
setx GPU_MAX_HEAP_SIZE 90	
setx GPU_MAX_USE_SYNC_OBJECTS 1	
setx GPU_SINGLE_ALLOC_PERCENT 90	
setx GPU_MAX_ALLOC_PERCENT 90	
setx GPU_MAX_SINGLE_ALLOC_PERCENT 90	
start /low Miner.exe